server:
  port: 8080
spring:
  profiles:
    active: prod
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret:
    key: ${jwt.secret.key}
  time:
    expiration: 1200000
url:
  front:
    dev: ${url.frontend.dev}
    prod: ${url.frontend.prod}
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${database.dev.url}/${database.dev.name}
    username: ${database.dev.username}
    password: ${database.dev.password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  url:
    backend:
      deploy: ${url.backend.dev}
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${database.prod.url}/${database.prod.name}
    username: ${database.prod.username}
    password: ${database.prod.password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  url:
    backend:
      deploy: ${url.backend.prod}
